### ISSUE TITLE
Valve Status - Settings - CSRs in Water Layers

### ISSUE THREAD

**Issue by JMurk** [JMurk/Valve_Hydrant_Mobile_Issues#1]
**Issue:**  When expanding the Water layer in the settings the Water CSR layers appear at the bottom.

![image](https://cloud.githubusercontent.com/assets/5805454/6881026/7ff77732-d523-11e4-92b5-5c4adb3926c9.png)

**Resolution:**  Please make sure the layers in the settings match the map service layers.

**Comment by jday3** [comment]
Done

**Comment by JMurk** [comment]
Confirmed complete.
