### ISSUE TITLE
Valve Status (v2) - Saving Plans - Clear Work Order ID Field When Type is Changed

### ISSUE THREAD

**Issue by JMurk** [JMurk/Valve_Hydrant_Mobile_Issues#10]
**Issue:**  When a user enters a Work Order ID and then changes the type to something else, the field correctly greys out but the input does not clear/delete.

![image](https://cloud.githubusercontent.com/assets/5805454/7026752/9cad912e-dd19-11e4-96f2-f8a1d40713bb.png)

**Resolution:**  Please change so that it clears when the type is changed.

--May need to check this in the Utility Viewer also--

**Comment by jday3** [comment]
Done. On utility viewer, I'm pretty sure the field appears and disappears based on the play type

**Comment by JMurk** [comment]
Confirmed complete.  The Utility Viewer hides the field, but I don't believe that it deletes the value if one had been entered previously.

**Comment by jday3** [comment]
fixed on utility viewer now
