### ISSUE TITLE
Valve Status (v2) - Saving Plans - Success Message

### ISSUE THREAD

**Issue by JMurk** [JMurk/Valve_Hydrant_Mobile_Issues#11]
Please update the confirmation message to read "The plan was saved successfully!"

![image](https://cloud.githubusercontent.com/assets/5805454/7026913/ad9a0200-dd1a-11e4-8cb4-fd9acb05e9c9.png)

**Comment by jday3** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
