### ISSUE TITLE
Valve Status - Results Window Misplaced After Screen Re-size

### ISSUE THREAD

**Issue by JMurk** [JMurk/Valve_Hydrant_Mobile_Issues#14]
**Issue:**  After a window re-size or flip of orientation on a tablet, the results window gets misplaced at the top of the map panel.

![image](https://cloud.githubusercontent.com/assets/5805454/7121083/e16c72ec-e1df-11e4-90dc-4084b0828c37.png)

**Resolution:**  Please investigate this issue when time permits.

**Comment by jday3** [comment]
Fixed. Just a tip - I recently found a useful tool that chrome has for emulating other (mobile) devices. When you are on the website press F12 and in the top left of the pane that opens click the phone icon 
![image](https://cloud.githubusercontent.com/assets/4439618/8306023/7492b0ca-1982-11e5-8047-77dbb836ce8e.png). Then you can select a device type from the drop down list.

**Comment by JMurk** [comment]
That is awesome. thanks!
