### ISSUE TITLE
Valve Status - Editing Existing Plan Details Button

### ISSUE THREAD

**Issue by JMurk** [JMurk/Valve_Hydrant_Mobile_Issues#15]
**Issue:**  When you open up an existing plan, the buttons on the Main Trace - Valve List panel are the same as if you are executing a plan.  Save Plan is not as relevant and is a bit confusing since the plan was already saved.

![image](https://cloud.githubusercontent.com/assets/5805454/7231101/1aebd1aa-e741-11e4-92a5-36125b0e5ed0.png)

**Resolution:** Can we change the name of the Save Plan button to "Edit Details" for existing plans that are opened?

**Comment by jday3** [comment]
Okay, it will show 'Edit Details' when opening an existing plan, but it will say 'Save Plan' after re-executing a plan because it is actually creating a new plan

**Comment by jday3** [comment]
Done on dev

**Comment by JMurk** [comment]
That works.  Confirmed complete.
