### ISSUE TITLE
Valve Status - Highlight Color

### ISSUE THREAD

**Issue by JMurk** [JMurk/Valve_Hydrant_Mobile_Issues#16]
**Issue:**  Users mentioned that the highlight color when selecting mains for a main trace is not noticeable enough.

![image](https://cloud.githubusercontent.com/assets/5805454/7688879/48d8b358-fd76-11e4-81b3-7c00090006cd.png)

**Resolution:**  Please change the highlight color to something the will stand out more.

**Comment by jday3** [comment]
Done on dev

**Comment by JMurk** [comment]
Looks good. Confirmed complete.
