### ISSUE TITLE
Valve Status - Add Geocoder Tool

### ISSUE THREAD

**Issue by JMurk** [JMurk/Valve_Hydrant_Mobile_Issues#18]
Please add the Geolocator/ address location from the other mobile applications.

Further, users would like the ability to search on Asset ID.  Can we add this to the same page?  They should be able to search for Water Mains (Main_ID) or Water Valves (Valve_ID).

**Comment by jday3** [comment]
Done, on dev

**Comment by JMurk** [comment]
Can you add the asset ID search to the same page?

**Comment by jday3** [comment]
What is the asset ID search?

**Comment by JMurk** [comment]
Per discussion

**Comment by jday3** [comment]
Done. Please provide feedback and a list of additional layers to search by in addition to Water Valves and Mains.

**Comment by JMurk** [comment]
Those two layers should work for now.  Confirmed complete.
