### ISSUE TITLE
Valve Status - Valve Details - Greyed Out Fields

### ISSUE THREAD

**Issue by JMurk** [JMurk/Valve_Hydrant_Mobile_Issues#2]
**Issue:**  On the Valve Details page, some of the fields are greyed out while others look normal.  There shouldn't be any need to grey out the text as they are all view-only.

![image](https://cloud.githubusercontent.com/assets/5805454/6881055/613b98c6-d525-11e4-806f-2d9b43decce9.png)

**Resolution:**  Please make all the text normal (not greyed out) on the Valve Details page.

**Comment by jday3** [comment]
Done

**Comment by JMurk** [comment]
Confirmed complete.
