### ISSUE TITLE
Valve Status - Valve Details - Two Structure Fields

### ISSUE THREAD

**Issue by JMurk** [JMurk/Valve_Hydrant_Mobile_Issues#20]
**Issue:** There are two 'Structure' fields in the Valve details form.  I believe the lower one is labeled incorrectly.

![image](https://cloud.githubusercontent.com/assets/5805454/8733646/d68eff38-2bd2-11e5-9714-ca34659ed9af.png)

**Resolution:"  Please look at the name of the database field populating that row and label it appropriately.

**Comment by jday3** [comment]
Fixed. It was supposed to be valve size

**Comment by JMurk** [comment]
Confirmed complete.
