### ISSUE TITLE
Valve Status - Valve Access & Valve Problem

### ISSUE THREAD

**Issue by JMurk** [JMurk/Valve_Hydrant_Mobile_Issues#21]
Please add an option of "NONE" to the Valve Access and Valve Status dropdowns.  This should be done in the Utility Viewer as well.

![image](https://cloud.githubusercontent.com/assets/5805454/8752608/2fc7dcfe-2c83-11e5-9921-683b94ba3a46.png)

![image](https://cloud.githubusercontent.com/assets/5805454/8752652/9107cdd0-2c83-11e5-9bd8-dcd48f433f0b.png)

**Comment by jday3** [comment]
Done in the mobile app and UV dev/prod

**Comment by JMurk** [comment]
Confirmed complete on all levels.
