### ISSUE TITLE
Valve Status Mobile - Push to Prod

### ISSUE THREAD

**Issue by JMurk** [JMurk/Valve_Hydrant_Mobile_Issues#22]
Please push the water valve status application to production.  At first, please do not grant anyone access.  We will grant user access as the City specifies.  

At this point, we just want it ready to go.

**Comment by jday3** [comment]
It is pushed to production. You can see the app in the admin portal, not the application portal. You are the only user with access. 

http://dpwview.baltimorecity.gov/water/valvetrackerwebapi/index.aspx

**Comment by JMurk** [comment]
We are beginning to roll this out to other users.  Please make this available in the portal.

**Comment by jday3** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
