### ISSUE TITLE
Valve Status - Turns Exercised

### ISSUE THREAD

**Issue by JMurk** [JMurk/Valve_Hydrant_Mobile_Issues#23]
**Issue:**  When the Exercised field is set to "Not Exercised," the Turns Exercised field is still required.

![image](https://cloud.githubusercontent.com/assets/5805454/12099320/8ff0e7ee-b2f5-11e5-9646-40551a73215d.png)

**Resolution:**  When Exercised is set to "Not Exercised," auto-populate Turns Exercised to 0.  Further, add a validation check to make sure that Turns Exercised is always = 0 when Exercised = "Not Exercised"

**Comment by kanglu666** [comment]
fixed on city dev

**Comment by JMurk** [comment]
Confirmed complete.
