### ISSUE TITLE
Hydrant - Settings - Turn Hydrant Layer On By Default

### ISSUE THREAD

**Issue by JMurk** [JMurk/Valve_Hydrant_Mobile_Issues#27]
**Update Description:**  Please update the application configuration so that the "Hydrants" layer is turned ON by default.

![image](https://cloud.githubusercontent.com/assets/5805454/12983970/b176ad7c-d0b9-11e5-8885-50a66bf711e7.png)

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
