### ISSUE TITLE
Hydrant - Settings - Hydrants Needing Inspection label

### ISSUE THREAD

**Issue by JMurk** [JMurk/Valve_Hydrant_Mobile_Issues#28]
**Update Description:**  Please remove the underscores from the Hydrants_Needing_Inspections layer label so that it reads "Hydrants Needing Inspections"

![image](https://cloud.githubusercontent.com/assets/5805454/12984059/141a2df0-d0ba-11e5-8542-3d11d0e16007.png)

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
