### ISSUE TITLE
Map - Add and Remove Services

### ISSUE THREAD

**Issue by JMurk** [JMurk/Valve_Hydrant_Mobile_Issues#29]
**Update Description:**  Please make the following adjustments to the map layers.

**Add:**
- 1108_Sewer as "Sewer" - Off by Default
- 1108_Storm as "Storm" - Off by Default
- Water_WorkOrders as "Water Work Orders - Off by Default
- 1108_Ortho as "Orthos" - Off by Default

**Remove:**
- Sewer CSRs
- Storm CSRs

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
