### ISSUE TITLE
Valve Status - Exiting Valve Info Screen

### ISSUE THREAD

**Issue by JMurk** [JMurk/Valve_Hydrant_Mobile_Issues#3]
**Issue:** When exiting the Valve Info screen (i.e. going to the map or settings page), there is no notification or apparent way to return to the screen.

**Resolution:**  I think the best way to handle this is to add a notification for when the user tries to navigate away from the info page that states "Navigating away from this page will lose all unsaved changes.  Continue?"  Then provide Yes/No options.

**Comment by jday3** [comment]
Done

**Comment by JMurk** [comment]
Confirmed complete.
