### ISSUE TITLE
Locator - Asset Locator - Add Hydrant

### ISSUE THREAD

**Issue by JMurk** [JMurk/Valve_Hydrant_Mobile_Issues#30]
**Update Description:**  Please add Hydrants as an option to the asset locator.  The search field will be HYDRANT_ID

![image](https://cloud.githubusercontent.com/assets/5805454/12985745/1ffd0400-d0c2-11e5-9569-e44491ee29c5.png)

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
