### ISSUE TITLE
Map - Home Button - Dev Version Returns to Prod Home

### ISSUE THREAD

**Issue by JMurk** [JMurk/Valve_Hydrant_Mobile_Issues#31]
**Issue:**  In the development version of the application, the home button navigates users to the production portal page.

![image](https://cloud.githubusercontent.com/assets/5805454/12985931/da09ef0c-d0c2-11e5-923e-dd1caa2040e6.png)

**Resolution:** Please update the link for the home button in the development version to return to the development application portal.

**Comment by kanglu666** [comment]
fixed

**Comment by JMurk** [comment]
Confirmed complete.
