### ISSUE TITLE
Hydrant - New Inspection - On Feature Selection

### ISSUE THREAD

**Issue by JMurk** [JMurk/Valve_Hydrant_Mobile_Issues#32]
**Issue:**  Upon selection of a hydrant feature, the system loads the hydrant info form with the most recent inspection populated.  Per requirement 3.1, the system should open a blank form for a new inspection.

**Resolution:**  On selection of a Hydrant feature, please load a form for a new inspection (do no insert yet) and pre-populate:

*Inspection ID
*Inspector
*Inspection Date

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
