### ISSUE TITLE
Hydrant - Inspection - Label Typos

### ISSUE THREAD

**Issue by JMurk** [JMurk/Valve_Hydrant_Mobile_Issues#34]
**Issue:**  The "Pitos(PSI)" field is misspelled.  Also, there should be spaces between labels and parenthesis.

![image](https://cloud.githubusercontent.com/assets/5805454/12986944/d6fadff6-d0c7-11e5-82e8-ee7ec1e92354.png)

**Resolution:** Please update to read "Pitot (PSI):" and "Flow Time (Minutes)".  Please be sure the space is included before the (

**Comment by rssidlowski** [comment]
Also change "Needs Paints?" to "Needs Paint?" and "Lubricated Nozzles" to "Lubricated Nozzles?".

**Comment by kanglu666** [comment]
updated

**Comment by JMurk** [comment]
Confirmed complete.
