### ISSUE TITLE
Hydrant - Discrepancy - Feature ID 

### ISSUE THREAD

**Issue by JMurk** [JMurk/Valve_Hydrant_Mobile_Issues#37]
**Issue:**  Discrepancies reported during a hydrant inspection do not write the Hydrant ID to the Feature ID field in the discrepancy feature class.

![image](https://cloud.githubusercontent.com/assets/5805454/12987507/5cf93920-d0ca-11e5-9e69-b47636026c51.png)

**Resolution:** Please populate the FEATURE_ID field with the HYDRANT_ID of the selected hydrant that the inspection is being performed on.

**Comment by kanglu666** [comment]
should be fixed, please test

**Comment by JMurk** [comment]
Confirmed complete.
