### ISSUE TITLE
Hydrant - Photos - Upload Date

### ISSUE THREAD

**Issue by JMurk** [JMurk/Valve_Hydrant_Mobile_Issues#38]
**Issue:**  Photos uploaded to Hydrant inspections do not store anything in the UPLOAD_DATE field.

![image](https://cloud.githubusercontent.com/assets/5805454/12988515/1d330d66-d0cf-11e5-9e43-050f2ad36a32.png)

**Resolution:** Upon upload of a photo, please populate the UPLOAD_DATE field with the current date/time.

**Comment by kanglu666** [comment]
should be fixed, please test

**Comment by JMurk** [comment]
Confirmed complete.
