### ISSUE TITLE
Hydrant - Edit Warning Message

### ISSUE THREAD

**Issue by JMurk** [JMurk/Valve_Hydrant_Mobile_Issues#42]
**Update Description:** Please update the following warning message:

![image](https://cloud.githubusercontent.com/assets/5805454/13019257/4e20190a-d19c-11e5-8ce4-1c579d43175b.png)

To read:  "Only the most recent inspections created within the past 7 days may be edited."

**Comment by kanglu666** [comment]
updated

**Comment by JMurk** [comment]
Confirmed complete.
