### ISSUE TITLE
Hydrant Status: error on save

### ISSUE THREAD

**Issue by rssidlowski** [JMurk/Valve_Hydrant_Mobile_Issues#48]
I added a new status and received the error below:
![erroronsave](https://cloud.githubusercontent.com/assets/5039052/13020692/d40e416a-d1a4-11e5-9b7a-9428c8609d46.PNG)

I left the required field Nozzle Count blank and that generated the error.
After adding in the nozzle count and saving again, it saved successfully.

**Comment by kanglu666** [comment]
fixed

**Comment by rssidlowski** [comment]
Retested.  Works fine now.
