### ISSUE TITLE
Valve Status - Historical Status Records - Disable Editing

### ISSUE THREAD

**Issue by JMurk** [JMurk/Valve_Hydrant_Mobile_Issues#5]
**Issue:**  The Utility Viewer does not allow for users to use historical records to edit the current valve status.  This rule should be matched in the mobile version as well.

**Resolution:**  Somehow have the application check to make sure they have the most recent status record open before making fields editable.

**Comment by jday3** [comment]
Done

**Comment by JMurk** [comment]
Confirmed complete.
