### ISSUE TITLE
Hydrant: navigation to map yields empty map

### ISSUE THREAD

**Issue by rssidlowski** [JMurk/Valve_Hydrant_Mobile_Issues#52]
When using the application and toggling between the hydrant info and the map, get an empty map.
![emptymap](https://cloud.githubusercontent.com/assets/5039052/13021904/befaf172-d1ab-11e5-8b9f-31acb556a3fc.PNG)

**Comment by kanglu666** [comment]
not a problem at my side，what browser were you using for testing? please use Chrome or Ipad

**Comment by rssidlowski** [comment]
Using Chrome.

**Comment by JMurk** [comment]
That has happened to me a few times, but I can't seem to recreate it now.  I'll keep an eye out.

**Comment by rssidlowski** [comment]
Closing for now, since unable to recreate consistently
