### ISSUE TITLE
Hydrant: Toggle between map and hydrant info: lose unsaved message

### ISSUE THREAD

**Issue by rssidlowski** [JMurk/Valve_Hydrant_Mobile_Issues#53]
When navigating between the map and the hydrant info pages, get prompted with the message below even if not editing (did not select the Edit button):
![loseunsaved](https://cloud.githubusercontent.com/assets/5039052/13022332/b198e7fc-d1ae-11e5-843d-77a0e67eb703.PNG)

The system should not prompt with the message unless there are actually unsaved changes.

I clicked on the OK in the above and now unable to toggle to the map.

**Comment by kanglu666** [comment]
this is how the app navigation designed. whenever you leave the form it shows the message.

**Comment by rssidlowski** [comment]
Is this correct behavior?

**Comment by JMurk** [comment]
That is probably how it was implemented, however for the user's convenience it should only prompt when there are unsaved edits.

**Comment by rssidlowski** [comment]
Lu, can you correct this?

**Comment by yousifmalik** [comment]
I added the code logic to detect any changes to form fields but the message still shows. Debugging it more, when identifying hydrant and switch to another tab (For example "Plans" or "Locate"), I found that the following fields are auto populated and therefore enable the message:
OBJECTID 
HYDRANT_ID
INSP_BY
INSP_ORG
INSP_DATE
STATUS

When select item from history and enable edit without making any changes and navigate to another tab, all above fields and the following fields marked as changed fields:
INSPECTION_ID
GIS_VERIFICATION 

Do we need to exclude these fields?

**Comment by rssidlowski** [comment]
Don't want to exclude these fields.  I will try to get clarification on the workflow this afternoon and provide more clear guidance.

**Comment by rssidlowski** [comment]
This may no longer be an issue if the workflow is redone to default to most recent history inspection instead of having a new inspection when click on the arrow from the identify results.
See #65.

**Comment by slmessier** [comment]
this issue does not apply due the current workflow having been updated. Since this issue no longer applies it will be closed.
