### ISSUE TITLE
Valve Status - Discrepancies

### ISSUE THREAD

**Issue by JMurk** [JMurk/Valve_Hydrant_Mobile_Issues#6]
**Issue:**  The discrepancy tool seems to get stuck on the loading screen when trying to submit a new discrepancy.  Also, I uploaded a photo and it never showed in the thumbnails pane.

![image](https://cloud.githubusercontent.com/assets/5805454/6881164/1b05216a-d52a-11e4-8431-e8b6dd582d33.png)

**Resolution:**  Please investigate and resolve accordingly.

**Comment by JMurk** [comment]
Also is there any check in place to see if the text entered for Description and Source exceeds the maximum amount of characters?

**Comment by jday3** [comment]
Were the discrepancy tables moved at some point? I think there may be an issue with the Images table.

**Comment by jday3** [comment]
Fixed. Added limits on the text fields also

**Comment by JMurk** [comment]
Confirmed complete.
