### ISSUE TITLE
Valve Status (v2) - Existing Plans - Filter Out Temp Plans

### ISSUE THREAD

**Issue by JMurk** [JMurk/Valve_Hydrant_Mobile_Issues#7]
**Issue:**  Each time a trace is executed, a new (temporary) plan is created, even if the user chooses not to save the plan.  We need to filter these temporary plans from the Existing Plans list.

![image](https://cloud.githubusercontent.com/assets/5805454/7024345/339388e2-dd0a-11e4-9d8a-04104382e97a.png)

**Resolution:**  You should be able to use the PLAN_TYPE field.  Where <> TEMP

**Comment by jday3** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
