### ISSUE TITLE
Valve Status (v2) - Exit Trace - Prompt Yes/No

### ISSUE THREAD

**Issue by JMurk** [JMurk/Valve_Hydrant_Mobile_Issues#8]
**Issue:** When exiting a trace, the system correctly prompts a warning message.  The Yes/No buttons are on opposite sides of all other message likes it.

![image](https://cloud.githubusercontent.com/assets/5805454/7025081/1b4c25fa-dd0f-11e4-80c1-15aa79d75d7d.png)

**Resolution:**  Please flip yes to the left and no to the right to keep consistent with other prompts in the app.

**Comment by JMurk** [comment]
Actually, we should probably also make this a browser pop-up instead of a application pop-up.  The application pop-ups have been known to be buggy.

**Comment by JMurk** [comment]
There is also a typo .... "race"

**Comment by JMurk** [comment]
Here is another one:

![image](https://cloud.githubusercontent.com/assets/5805454/7025411/77c2fd0c-dd11-11e4-9afc-bb7aa80c0dd9.png)

**Comment by jday3** [comment]
Done, now all popups will be browser popups

**Comment by JMurk** [comment]
Confirmed complete.
