### ISSUE TITLE
Valves & Hydrants - Save warning after save

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Valve_Hydrant_Mobile_Issues#87]
If the user updates a valve and saves it, when they attempt to navigate back to the map they are met with the warning that unsaved changes will be lost.  Please disable this warning if the user has already pressed the save button.

![image](https://cloud.githubusercontent.com/assets/7118831/17624568/1c9b3458-6073-11e6-81ce-8ade8c2f27f2.png)

**Comment by taojun545** [comment]
Updated both on PROD and DEV.

The user will not see the warning until the form is on editing model.

**Comment by alanfoster99** [comment]
Confirmed and closing
