### ISSUE TITLE
Valve Status (v2) - Saving Plans - Work Order ID Field

### ISSUE THREAD

**Issue by JMurk** [JMurk/Valve_Hydrant_Mobile_Issues#9]
Please make a couple minor changes to the Work Order ID field in the Shutdown Plan form.
1. Add a separator between the input field and the search field so it doesn't look like the same input line.
2. Change the search query so that the entered text looks for records that start with what is entered.

![image](https://cloud.githubusercontent.com/assets/5805454/7026618/d6f47ccc-dd18-11e4-882a-503494944173.png)

**Comment by jday3** [comment]
Done

**Comment by JMurk** [comment]
Confirmed complete.
